### ISSUE TITLE
Mysqldump error | 求索

### ISSUE THREAD

**Issue by xiemx** [xiemx/xray#131]
https://blog.xiemx.com/2019/05/06/mysqldump-error/ 

 现象1234[root@FCHK-instance ~]# mysqldump --host rm-xxxxxxxxxxx.mysql.rds.aliyuncs.com -u xxxx -p --databases visa &gt; hk.sqlEnter password:Warning: A partial dump from a server that has GTIDs will by

**Comment by wangshiling** [comment]
test for devops
